#define DL  DiffNode (node->left,  param)
#define DR  DiffNode (node->right, param)
#define CR  CopyNode (node->right, node)
#define CL  CopyNode (node->left,  node)
#define CN(val)    CreateNode (val,  TYPE_CONST)
#define ADD(l, r)  CreateNode ('+',  TYPE_OP,     l, r)
#define SUB(l, r)  CreateNode ('-',  TYPE_OP,     l, r)
#define MUL(l, r)  CreateNode ('*',  TYPE_OP,     l, r)
#define DIV(l, r)  CreateNode ('/',  TYPE_OP,     l, r)
#define POW(l, r)  CreateNode ('^',  TYPE_OP,     l, r)
#define DSIN(val)  CreateNode (SIN,  TYPE_UNARY,  val)
#define DCOS(val)  CreateNode (COS,  TYPE_UNARY,  val)
#define DASIN(val) CreateNode (ASIN, TYPE_UNARY,  val)
#define DACOS(val) CreateNode (ACOS, TYPE_UNARY,  val)
#define DLN(val)   CreateNode (LN,   TYPE_UNARY,  val)
